namespace UserAuthApi.Models
{
    public class User
    {
        public int Id { get; set; } // primary key, needed to uniquely identify a user
                                    // This is automatically generated by the database, no need to set it manually
                                    // but could be set manually if needed
        public string Email { get; set; }
        public string Password { get; set; }
    }
}
